name: 'build'

on:
  push:
    branches: 
      - master
      - feature/*
      - hotfix/*
    tags:
      - linux-msft-wsl-*
  pull_request: {}
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        run: |
          sudo apt-get update -yqq
          sudo bash build-kernel
          cp linux-msft-wsl-*/vmlinux .

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: jonatans-custom-linux-kernel
          path: vmlinux

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jonatans-custom-linux-kernel
